### ISSUE TITLE
Error while running findFeatures

### ISSUE THREAD

**Issue by tsufz** [rickhelmus/patRoon#16] opened 2020-11-07 11:02 UTC
Hi Rick,
I observed an error while running `fList <- findFeatures(anaInfo, "xcms3", verbose = TRUE, param = pick_param)`.

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'X' in selecting a method for function 'bplapply': could not find function "featureData"
```

I concluded that this error is relatd to `xcms`. As soon I load `xcsms`, the error is gone. Thus, I checked the `xcms` code, but did not found any conclusive code. Maybe @sneumann or @jorainer have an idea?

Thus, I guess that some function import is missing in `patRoon` to avoid additional loading of `xcms`.

Best,
Tobias

`sessionInfo()`
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] xcms_3.12.0         MSnbase_2.16.0      ProtGenerics_1.22.0 S4Vectors_0.28.0    mzR_2.24.0          Rcpp_1.0.5         
 [7] BiocParallel_1.24.0 Biobase_2.50.0      BiocGenerics_0.36.0 data.table_1.13.2   patRoon_1.0.4       forcats_0.5.0      
[13] stringr_1.4.0       dplyr_1.0.2         purrr_0.3.4         readr_1.4.0         tidyr_1.1.2         tibble_3.0.4       
[19] ggplot2_3.3.2       tidyverse_1.3.0    

loaded via a namespace (and not attached):
  [1] snow_0.4-3                  readxl_1.3.1                backports_1.2.0             Hmisc_4.4-1                
  [5] plyr_1.8.6                  igraph_1.2.6                CAMERA_1.46.0               splines_4.0.3              
  [9] GenomeInfoDb_1.26.0         TH.data_1.0-10              digest_0.6.27               foreach_1.5.1              
 [13] htmltools_0.5.0             fansi_0.4.1                 memoise_1.1.0               magrittr_1.5               
 [17] checkmate_2.0.0             cluster_2.1.0               doParallel_1.0.16           limma_3.46.0               
 [21] modelr_0.1.8                matrixStats_0.57.0          sandwich_3.0-0              jpeg_0.1-8.1               
 [25] colorspace_1.4-1            blob_1.2.1                  rvest_0.3.6                 haven_2.3.1                
 [29] rbibutils_1.4               xfun_0.19                   crayon_1.3.4                RCurl_1.98-1.2             
 [33] jsonlite_1.7.1              graph_1.68.0                impute_1.64.0               survival_3.2-7             
 [37] zoo_1.8-8                   iterators_1.0.13            glue_1.4.2                  gtable_0.3.0               
 [41] zlibbioc_1.36.0             emmeans_1.5.2-1             XVector_0.30.0              DelayedArray_0.16.0        
 [45] DEoptimR_1.0-8              scales_1.1.1                vsn_3.58.0                  mvtnorm_1.1-1              
 [49] DBI_1.1.0                   xtable_1.8-4                htmlTable_2.1.0             bit_4.0.4                  
 [53] foreign_0.8-80              preprocessCore_1.52.0       Formula_1.2-4               MsCoreUtils_1.2.0          
 [57] htmlwidgets_1.5.2           httr_1.4.2                  RColorBrewer_1.1-2          ellipsis_0.3.1             
 [61] pkgconfig_2.0.3             XML_3.99-0.5                nnet_7.3-14                 dbplyr_2.0.0               
 [65] tidyselect_1.1.0            rlang_0.4.8                 later_1.1.0.1               cellranger_1.1.0           
 [69] munsell_0.5.0               tools_4.0.3                 cli_2.1.0                   RSQLite_2.2.1              
 [73] generics_0.1.0              broom_0.7.2                 fastmap_1.0.1               mzID_1.28.0                
 [77] bit64_4.0.5                 fs_1.5.0                    knitr_1.30                  robustbase_0.93-6          
 [81] RANN_2.6.1                  packrat_0.5.0               ncdf4_1.17                  RBGL_1.66.0                
 [85] mime_0.9                    xml2_1.3.2                  compiler_4.0.3              rstudioapi_0.11            
 [89] png_0.1-7                   affyio_1.60.0               reprex_0.3.0                MassSpecWavelet_1.56.0     
 [93] stringi_1.5.3               lattice_0.20-41             Matrix_1.2-18               vctrs_0.3.4                
 [97] pillar_1.4.6                lifecycle_0.2.0             BiocManager_1.30.10         Rdpack_2.0                 
[101] MALDIquant_1.19.3           estimability_1.3            bitops_1.0-6                gbRd_0.4-11                
[105] httpuv_1.5.4                GenomicRanges_1.42.0        R6_2.5.0                    latticeExtra_0.6-29        
[109] pcaMethods_1.82.0           affy_1.68.0                 promises_1.1.1              gridExtra_2.3              
[113] IRanges_2.24.0              codetools_0.2-18            MASS_7.3-53                 assertthat_0.2.1           
[117] SummarizedExperiment_1.20.0 withr_2.3.0                 multcomp_1.4-14             GenomeInfoDbData_1.2.4     
[121] hms_0.5.3                   fst_0.9.4                   grid_4.0.3                  rpart_4.1-15               
[125] coda_0.19-4                 MatrixGenerics_1.2.0        rsm_2.10.2                  shiny_1.5.0                
[129] lubridate_1.7.9             base64enc_0.1-3

**Comment by rickhelmus** [comment] 2020-11-09 12:46
Hi Tobias,

Thanks for the report!

I can't find a way to reproduce your error. Still, `featureData` is definitely something coming from `xcms` / `MSnbase`, so it seems like it may be a missing export somewhere on their side.

Perhaps interesting to try: can you disable parallelization and see if it still happens? E.g. by setting the `BiocParallel` backend to `SerialParam`

**Comment by jorainer** [comment] 2020-11-09 13:05
Am also chiming in - yes, `featureData` is defined in `MSnbase` - and yes, there seems to be a missing export of this method (still manual pre-roxygen NAMESPACE...). I will ensure we will add that export to `MSnbase`. 

Another hint to the error: on Windows a socket-based parallel processing is used, i.e. each parallel process is it's own R process with its own memory and loaded libraries. It can thus happen that you have to load the `xcms` library explicitely in the parallel process.

**Comment by jorainer** [comment] 2020-11-09 13:08
PS: @rickhelmus , I would suggest to use `fData` instead of `featureData`. `fData` returns a `data.frame` while `featureData` returns an `AnnotatedDataFrame` - an object which I find pretty un-necessary. And `fData` is properly exported :)

**Comment by rickhelmus** [comment] 2020-11-09 13:13
Hi @jorainer thanks for chiming in! Good to know about `featureData`/`fData`. Although to be honest I'm not using either of them at the moment ... :-) I guess the socket parallelization might have triggered this somehow.

Anyway, seems I can close the issue.

**Closed by rickhelmus** 2020-11-09 13:13 UTC
